config/routes.rb
Rails.application.routes.draw do
  resources :events, only: [:new, :create, :show, :index]

  resources :sessions, only: [:new, :create, :destroy]
  root 'sessions#new'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'

  resources :users, only: [:new, :create, :show, :index]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
	belongs_to :creator, :class_name => "User"

	has_many :invites, :foreign_key => "attended_event_id"
	has_many :attendees, :through => :invites

	scope :upcoming, -> { where("Date >= ?", Date.today).order('Date ASC') }
	scope :past, -> { where("Date < ?", Date.today).order('Date DESC') }
end

app/models/invite.rb
class Invite < ApplicationRecord
	belongs_to :attendee, class_name: "User"
	belongs_to :attended_event, class_name: "Event"
end

app/models/user.rb
class User < ApplicationRecord
	has_many :events, :foreign_key => :creator_id

	has_many :invites, :foreign_key => :attendee_id
	has_many :attended_events, :through => :invites

	def upcoming_events
		self.attended_events.upcoming
	end

	def previous_events
		self.attended_events.past
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def new
  	@event = Event.new
  end

  def create
  	@user = current_user
  	@event = @user.events.build(event_params)
  	if @event.save
  		redirect_to event_path(@event)
  	else
  		render 'new'
  	end
  end

  def show
  	@event = Event.find(params[:id])
  	@upcoming_events = Event.upcoming
  	@previous_events = Event.past
  end

  def index
  	@events = Event.all
  end


  private
  	def event_params
  		params.require(:event).permit(:location, :date, :description)
  	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	
  def new
  end

  def create
  	user = User.find_by(username: params[:session][:username].downcase)
  	if user
  		sign_in(user)
  		redirect_to user
  	else
  		render 'new'
  	end
  end

  def destroy
  	sign_out
  	redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  	@user = User.new
  end

  def create
  end

  def show
  	@user = User.find_by(params[:id])
  end

  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def sign_in(user)
		username = user.username
		cookies.permanent[:username] = username
		self.current_user = user
	end

	def current_user=(user)
		@current_user = user
	end

	def current_user
		@current_user ||= User.find_by(username: cookies[:username])
	end

	def sign_out
		cookies.delete(:username)
		@current_user = nil
	end
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/events/create.html.erb
<h1>Events#create</h1>
<p>Find me in app/views/events/create.html.erb</p>

app/views/events/index.html.erb
<h1>Events</h1>

<h4>Upcoming:</h4>
<% if Event.upcoming.any? %>
<ul><% Event.upcoming.each do |event| %>
	<li><%= link_to event.description, event_path(event) %></li>
<% end %>
</ul>
<% end %>

<h4>Past:</h4>
<% if Event.past.any? %>
<ul><% Event.past.each do |event| %>
	<li><%= link_to event.description, event_path(event) %></li>
<% end %>
</ul>
<% end %>

<p>Find me in app/views/events/index.html.erb</p>

app/views/events/new.html.erb
<%= form_for(:event, url: events_path) do |f| %>
	
	<%= f.label :description %>
	<%= f.text_field :description %>

	<%= f.submit "Create Event" %>
<% end %>

app/views/events/show.html.erb
<h1>Events#show</h1>
<h3><%= @event.description %></h3>
<%= link_to @event.creator.username, user_path(@event.creator) %> created this event
<h3>People attending this event:</h3>
<ul><% @event.attendees.each do |attendee| %>
	<li><%= link_to attendee.username, user_path(@event.attendees.ids) %></li>
</ul>
<% end %>
<p>Find me in app/views/events/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvents</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_user_home.html.erb
<h5>You are signed in as <%= @user.username %></h5>
<h3>You have created a total of <%= @user.events.length%>
  events</h3>

<h3>Events you are attending...</h3>
<h4>Upcoming:</h4>
<% if @user.upcoming_events.any? %>
<ul><% @user.upcoming_events.each do |event| %>
	<li><%= link_to event.description, event_path(event) %></li>
<% end %>
</ul>
<% end %>

<h4>Past:</h4>
<% if @user.previous_events.any? %>
<ul><% @user.previous_events.each do |event| %>
	<li><%= link_to event.description, event_path(event) %></li>
<% end %>
</ul>
<% end %>

app/views/users/new.html.erb
<h1>User#new</h1>
<h1>Fuck you Ali</h1>

<p>Find me in app/views/user/new.html.erb</p>

app/views/users/show.html.erb
<h1>User#show</h1>
<%= render 'shared/user_home' %>


<p><%= link_to 'Sign out', signout_path, method: "delete" %></p>
<p><%= link_to 'Create new event', new_event_path %></p>
<p><%= link_to 'All Event Listings', events_path %></p>
<p>Find me in app/views/user/show.html.erb</p>